## RNN(Recurrent Neural Network) : 순환 신경망
#### 순서가 있는 시퀀스 데이터, time series data(시계열 데이터)를 입력하여 예측

In [1]:
# rnn_basic
import numpy as np
import tensorflow as tf

### One cell: 4 (input_dim) in 2 (hidden_size)

![image](https://cloud.githubusercontent.com/assets/901975/23348727/cc981856-fce7-11e6-83ea-4b187473466b.png)

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
# One cell RNN input_dim (4) -> output_dim (2)
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size) 
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True) 
                               # return_sequences=True : 출력으로 시퀀스 전체를 출력할지 여부를 설정
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.7361645   0.31542835]]], shape: (1, 1, 2)
states: [[-0.7361645   0.31542835]], shape: (1, 2)


In [4]:
# 위 코드와  동일한 결과
rnn = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True,
                       return_state=True) 

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.5391797  -0.19243446]]], shape: (1, 1, 2)
states: [[-0.5391797  -0.19243446]], shape: (1, 2)


### Unfolding to n sequences

![image](https://cloud.githubusercontent.com/assets/901975/23383634/649efd0a-fd82-11e6-925d-8041242743b0.png)

In [5]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[-0.6200635   0.48090386]
  [-0.89200085  0.21766748]
  [-0.5686367   0.9279554 ]
  [-0.8801365   0.8786408 ]
  [-0.79642576  0.8286864 ]]], shape: (1, 5, 2) 

states: [[-0.79642576  0.8286864 ]], shape: (1, 2)


### Batching input

![image](https://cloud.githubusercontent.com/assets/901975/23383681/9943a9fc-fd82-11e6-8121-bd187994e249.png)

In [6]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = tf.keras.layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[-0.43599156 -0.7400084 ]
  [-0.6684262  -0.73072714]
  [-0.077897   -0.76451856]
  [ 0.293633   -0.8976113 ]
  [-0.20928256 -0.6274788 ]]

 [[ 0.02958793 -0.6289802 ]
  [-0.19560911 -0.34595686]
  [ 0.4825249  -0.7957691 ]
  [ 0.581232   -0.95527947]
  [ 0.5483403  -0.9686645 ]]

 [[ 0.72216785 -0.7581726 ]
  [ 0.69424105 -0.9665813 ]
  [-0.19472456 -0.9569147 ]
  [-0.6641209  -0.8495764 ]
  [-0.16017121 -0.79748964]]], shape: (3, 5, 2) 

states: [[-0.20928256 -0.6274788 ]
 [ 0.5483403  -0.9686645 ]
 [-0.16017121 -0.79748964]], shape: (3, 2)
